service: psg2

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs4.3
  memorySize: 256

  environment:
    DEPLOYMENT: ${self:service}-${opt:stage, self:provider.stage}

  stage: dev
  region: eu-west-1

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:s3:::"
            - "Ref" : "ServerlessDeploymentBucket"
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DEPLOYMENT}-*models"

#package:
  #include:
    #- src/**
  #exclude:
    #- exclude-me.js
    #- exclude-me-dir/**

functions:

  series-list:
    handler: src/series.list
    events:
      - http:
          path: series
          method: get
          cors: true
  series-get:
    handler: src/series.get
    events:
      - http:
          path: series/{name}
          method: get
          cors: true
          parameters:
            path:
              name: true
  series-create:
    handler: src/series.create
    events:
      - http:
          path: series/{name}
          method: post
          cors: true
          parameters:
            path:
              name: true
  series-games:
    handler: src/series.games
    events:
      - http:
          path: series/{name}/games
          method: get
          cors: true
          parameters:
            path:
              name: true

  player-get:
    handler: src/player.get
    events:
      - http:
          path: player/{name}
          method: get
          cors: true
          parameters:
            path:
              name: true
  player-create:
    handler: src/player.create
    events:
      - http:
          path: player/{name}
          method: post
          cors: true
          parameters:
            path:
              name: true
  player-add-to-series:
    handler: src/player.addToSeries
    events:
      - http:
          path: player/{name}/series
          method: post
          cors: true
          parameters:
            path:
              name: true
  game-get:
    handler: src/game.get
    events:
      - http:
          path: game/{id}
          method: get
          cors: true
  game-create:
    handler: src/game.create
    events:
      - http:
          path: game
          method: post
          cors: true
#    Define function environment variables here
#    environment:
#      variable2: value2

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
#

resources:
  Resources:
    ModelsDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DEPLOYMENT}-models
    RangeModelsDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
          -
            AttributeName: range
            AttributeType: N
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
          -
            AttributeName: range
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DEPLOYMENT}-rangemodels
